title = "YuëH"
baseURL = "https://yuehtheband.com"
theme = ["ananke"]
#resourceDir = "../resources"
cleanDestinationDir = true
defaultContentLanguage = 'en'

googleAnalytics = ""
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "YuëH"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "YuëH Fr"
    weight = 2
    contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
#site_logo = "./content/images/logo/logo2.jpg"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 5
showTaxonomies = true
#mainSections = ['music', 'tour']

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "instagram",
  "facebook",
  "youtube",
  "bandcamp",
  "soundcloud",
  "spotify",
  "deezer"
]

[params.ananke.social.instagram]
profilelink = "https://www.instagram.com/yueh_the_band?igsh=NTk5c3FkOWs4dWNq"

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/share/1BzJKavPX9/"

[params.ananke.social.bandcamp]
profilelink = "https://yuehtheband.bandcamp.com/music"

[params.ananke.social.soundcloud]
profilelink = "https://soundcloud.com/user-46427240-392550333"

[params.ananke.social.spotify]
profilelink = "https://open.spotify.com/artist/5UENHG8co9gezY6UiJG9Ay"

[params.ananke.social.deezer]
profilelink = "https://www.deezer.com/us/album/419695267"

